#!/usr/bin/env python3
"""Emit web/styles/curriculum-themes.css from schemas/themes/*.json"""
from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    themes_dir = root / "schemas" / "themes"
    out = root / "web" / "styles" / "curriculum-themes.css"
    index = json.loads((themes_dir / "index.json").read_text(encoding="utf-8"))
    lines = [
        "/* Auto-generated by backend/generate_theme_css.py — do not hand-edit; re-run script after theme changes. */",
        "/* Apply: set document.documentElement.dataset.curTheme = '<id>' or data-cur-theme on <html>. */",
        "",
    ]
    for entry in index["themes"]:
        tid = entry["id"]
        data = json.loads((themes_dir / entry["file"]).read_text(encoding="utf-8"))
        lines.append(f'[data-cur-theme="{tid}"] {{')
        for k, v in data["css"].items():
            lines.append(f"  {k}: {v};")
        lines.append("}")
        lines.append("")
    default = index.get("default_theme_id", "paper-sf-light")
    lines.append(f":root:not([data-cur-theme]) {{")
    data = json.loads((themes_dir / next(e["file"] for e in index["themes"] if e["id"] == default)).read_text(encoding="utf-8"))
    for k, v in data["css"].items():
        lines.append(f"  {k}: {v};")
    lines.append("}")
    lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
